--[=[
 d888b  db    db d888888b      .d888b.      db      db    db  .d8b.  
88' Y8b 88    88   `88'        VP  `8D      88      88    88 d8' `8b 
88      88    88    88            odD'      88      88    88 88ooo88 
88  ooo 88    88    88          .88'        88      88    88 88~~~88 
88. ~8~ 88b  d88   .88.        j88.         88booo. 88b  d88 88   88    @uniquadev
 Y888P  ~Y8888P' Y888888P      888888D      Y88888P ~Y8888P' YP   YP  CONVERTER 

designed using localmaze gui creator
]=]

-- Instances: 31 | Scripts: 12 | Modules: 0 | Tags: 0
local LMG2L = {};

-- Players.9x7x9x4x6.PlayerGui.ScreenGui
LMG2L["ScreenGui_1"] = Instance.new("ScreenGui", game:GetService("CoreGui"));
LMG2L["ScreenGui_1"]["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling;
LMG2L["ScreenGui_1"]["ResetOnSpawn"] = false;


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame
LMG2L["Frame_2"] = Instance.new("Frame", LMG2L["ScreenGui_1"]);
LMG2L["Frame_2"]["BorderSizePixel"] = 0;
LMG2L["Frame_2"]["BackgroundColor3"] = Color3.fromRGB(161, 255, 102);
LMG2L["Frame_2"]["Size"] = UDim2.new(0.66023, 0, 0.92261, 0);
LMG2L["Frame_2"]["Position"] = UDim2.new(0.09467, 0, 0.00599, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextLabel
LMG2L["TextLabel_3"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["TextLabel_3"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_3"]["TextSize"] = 24;
LMG2L["TextLabel_3"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextLabel_3"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_3"]["FontFace"] = Font.new([[rbxasset://fonts/families/SourceSansPro.json]], Enum.FontWeight.Bold, Enum.FontStyle.Normal);
LMG2L["TextLabel_3"]["BackgroundTransparency"] = 1;
LMG2L["TextLabel_3"]["Size"] = UDim2.new(0.9283, 0, 0.0974, 0);
LMG2L["TextLabel_3"]["Text"] = [[9x7x9x4x6 Gui F3X | Beta V0.1]];
LMG2L["TextLabel_3"]["Position"] = UDim2.new(0.0717, 0, 0, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.ImageLabel
LMG2L["ImageLabel_4"] = Instance.new("ImageLabel", LMG2L["Frame_2"]);
LMG2L["ImageLabel_4"]["BorderSizePixel"] = 0;
LMG2L["ImageLabel_4"]["BackgroundColor3"] = Color3.fromRGB(0, 0, 0);
-- LMG2L["ImageLabel_4"]["ImageContent"] = ;
LMG2L["ImageLabel_4"]["Image"] = [[rbxassetid://122639036587569]];
LMG2L["ImageLabel_4"]["Size"] = UDim2.new(0.06415, 0, 0.0974, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_5"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_5"]["BorderSizePixel"] = 0;
LMG2L["TextButton_5"]["BackgroundColor3"] = Color3.fromRGB(255, 61, 61);
LMG2L["TextButton_5"]["Size"] = UDim2.new(0.2, 0, 0.06494, 0);
LMG2L["TextButton_5"]["Text"] = [[]];
LMG2L["TextButton_5"]["Position"] = UDim2.new(0.78868, 0, 0.02597, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.UICorner
LMG2L["UICorner_6"] = Instance.new("UICorner", LMG2L["TextButton_5"]);
LMG2L["UICorner_6"]["CornerRadius"] = UDim.new(0, 9999);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_7"] = Instance.new("LocalScript", LMG2L["TextButton_5"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_8"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_8"]["BorderSizePixel"] = 0;
LMG2L["TextButton_8"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_8"]["Size"] = UDim2.new(0.36226, 0, 0.12987, 0);
LMG2L["TextButton_8"]["Text"] = [[Btools]];
LMG2L["TextButton_8"]["Position"] = UDim2.new(0.01887, 0, 0.12338, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_9"] = Instance.new("LocalScript", LMG2L["TextButton_8"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_a"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_a"]["BorderSizePixel"] = 0;
LMG2L["TextButton_a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_a"]["Size"] = UDim2.new(0.36226, 0, 0.12987, 0);
LMG2L["TextButton_a"]["Text"] = [[Mesagge]];
LMG2L["TextButton_a"]["Position"] = UDim2.new(0.40377, 0, 0.12338, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_b"] = Instance.new("LocalScript", LMG2L["TextButton_a"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_c"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_c"]["BorderSizePixel"] = 0;
LMG2L["TextButton_c"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_c"]["Size"] = UDim2.new(0.2, 0, 0.12987, 0);
LMG2L["TextButton_c"]["Text"] = [[Hint]];
LMG2L["TextButton_c"]["Position"] = UDim2.new(0.78491, 0, 0.12338, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_d"] = Instance.new("LocalScript", LMG2L["TextButton_c"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_e"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_e"]["BorderSizePixel"] = 0;
LMG2L["TextButton_e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_e"]["Size"] = UDim2.new(0.36226, 0, 0.12987, 0);
LMG2L["TextButton_e"]["Text"] = [[Spam Decal]];
LMG2L["TextButton_e"]["Position"] = UDim2.new(0.01887, 0, 0.31818, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_f"] = Instance.new("LocalScript", LMG2L["TextButton_e"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_10"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_10"]["BorderSizePixel"] = 0;
LMG2L["TextButton_10"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_10"]["Size"] = UDim2.new(0.36226, 0, 0.12987, 0);
LMG2L["TextButton_10"]["Text"] = [[HD Skybox Trippy]];
LMG2L["TextButton_10"]["Position"] = UDim2.new(0.40377, 0, 0.31818, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_11"] = Instance.new("LocalScript", LMG2L["TextButton_10"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_12"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_12"]["BorderSizePixel"] = 0;
LMG2L["TextButton_12"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_12"]["Size"] = UDim2.new(0.2, 0, 0.12987, 0);
LMG2L["TextButton_12"]["Text"] = [[Theme]];
LMG2L["TextButton_12"]["Position"] = UDim2.new(0.78491, 0, 0.31818, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_13"] = Instance.new("LocalScript", LMG2L["TextButton_12"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_14"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_14"]["BorderSizePixel"] = 0;
LMG2L["TextButton_14"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_14"]["Size"] = UDim2.new(0.36226, 0, 0.12987, 0);
LMG2L["TextButton_14"]["Text"] = [[Baseplate]];
LMG2L["TextButton_14"]["Position"] = UDim2.new(0.01887, 0, 0.5, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_15"] = Instance.new("LocalScript", LMG2L["TextButton_14"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_16"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_16"]["BorderSizePixel"] = 0;
LMG2L["TextButton_16"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_16"]["Size"] = UDim2.new(0.36226, 0, 0.12987, 0);
LMG2L["TextButton_16"]["Text"] = [[Floating Pad]];
LMG2L["TextButton_16"]["Position"] = UDim2.new(0.40377, 0, 0.5, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_17"] = Instance.new("LocalScript", LMG2L["TextButton_16"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_18"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_18"]["BorderSizePixel"] = 0;
LMG2L["TextButton_18"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_18"]["Size"] = UDim2.new(0.2, 0, 0.12987, 0);
LMG2L["TextButton_18"]["Text"] = [[Blood Pop 2]];
LMG2L["TextButton_18"]["Position"] = UDim2.new(0.78491, 0, 0.5, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_19"] = Instance.new("LocalScript", LMG2L["TextButton_18"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextLabel
LMG2L["TextLabel_1a"] = Instance.new("TextLabel", LMG2L["Frame_2"]);
LMG2L["TextLabel_1a"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_1a"]["TextSize"] = 48;
LMG2L["TextLabel_1a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_1a"]["FontFace"] = Font.new([[rbxasset://fonts/families/SourceSansPro.json]], Enum.FontWeight.Bold, Enum.FontStyle.Normal);
LMG2L["TextLabel_1a"]["TextColor3"] = Color3.fromRGB(0, 0, 0);
LMG2L["TextLabel_1a"]["Size"] = UDim2.new(0.96226, 0, 0.2987, 0);
LMG2L["TextLabel_1a"]["Text"] = [[Coming Soon! ]];
LMG2L["TextLabel_1a"]["Position"] = UDim2.new(0.01887, 0, 0.65584, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton
LMG2L["TextButton_1b"] = Instance.new("TextButton", LMG2L["Frame_2"]);
LMG2L["TextButton_1b"]["BorderSizePixel"] = 0;
LMG2L["TextButton_1b"]["TextSize"] = 14;
LMG2L["TextButton_1b"]["TextColor3"] = Color3.fromRGB(0, 0, 0);
LMG2L["TextButton_1b"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_1b"]["FontFace"] = Font.new([[rbxasset://fonts/families/SourceSansPro.json]], Enum.FontWeight.Bold, Enum.FontStyle.Normal);
LMG2L["TextButton_1b"]["Size"] = UDim2.new(0.2, 0, 0.06494, 0);
LMG2L["TextButton_1b"]["Text"] = [[Credits]];
LMG2L["TextButton_1b"]["Position"] = UDim2.new(0.57358, 0, 0.02597, 0);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.UICorner
LMG2L["UICorner_1c"] = Instance.new("UICorner", LMG2L["TextButton_1b"]);
LMG2L["UICorner_1c"]["CornerRadius"] = UDim.new(0, 9999);


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
LMG2L["LocalScript_1d"] = Instance.new("LocalScript", LMG2L["TextButton_1b"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.LocalScript
LMG2L["LocalScript_1e"] = Instance.new("LocalScript", LMG2L["Frame_2"]);



-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.UIAspectRatioConstraint
LMG2L["UIAspectRatioConstraint_1f"] = Instance.new("UIAspectRatioConstraint", LMG2L["Frame_2"]);
LMG2L["UIAspectRatioConstraint_1f"]["AspectRatio"] = 1.72078;


-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_7()
	local script = LMG2L["LocalScript_7"];
  end;
task.spawn(C_7);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_9()
	local script = LMG2L["LocalScript_9"];
	local getbutton = script.parent
  getbutton.MouseButton1Down:connect(function()
  local ReplicatedStorage = game:GetService("ReplicatedStorage")
	local RequestCommand = ReplicatedStorage:WaitForChild("HDAdminHDClient").Signals.RequestCommandSilent

	RequestCommand:InvokeServer(";btools")
  end) 
end;
task.spawn(C_9);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_b()
	local script = LMG2L["LocalScript_b"];
	local getbutton = script.parent
  getbutton.MouseButton1Down:connect(function()
  local ReplicatedStorage = game:GetService("ReplicatedStorage")
	local RequestCommand = ReplicatedStorage:WaitForChild("HDAdminHDClient").Signals.RequestCommandSilent

	RequestCommand:InvokeServer(";sm haxxed by 9x7x9x4x6 lol")
  end) 

end;
task.spawn(C_b);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_d()
	local script = LMG2L["LocalScript_d"];
	local getbutton = script.parent
  getbutton.MouseButton1Down:connect(function()
  local ReplicatedStorage = game:GetService("ReplicatedStorage")
	local RequestCommand = ReplicatedStorage:WaitForChild("HDAdminHDClient").Signals.RequestCommandSilent

	RequestCommand:InvokeServer(";ServerHint Get Hacked By 9x7x9x4x6")
  end) 

end;
task.spawn(C_d);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_f()
	local script = LMG2L["LocalScript_f"];
	
end;
task.spawn(C_f);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_11()
	local script = LMG2L["LocalScript_11"];
	
end;
task.spawn(C_11);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_13()
	local script = LMG2L["LocalScript_13"];
	
end;
task.spawn(C_13);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_15()
	local script = LMG2L["LocalScript_15"];
	
end;
task.spawn(C_15);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_17()
	local script = LMG2L["LocalScript_17"];
	
end;
task.spawn(C_17);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_19()
	local script = LMG2L["LocalScript_19"];
	
end;
task.spawn(C_19);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.TextButton.LocalScript
local function C_1d()
	local script = LMG2L["LocalScript_1d"];
	
end;
task.spawn(C_1d);
-- Players.9x7x9x4x6.PlayerGui.ScreenGui.Frame.LocalScript
local function C_1e()
	local script = LMG2L["LocalScript_1e"];
	
end;
task.spawn(C_1e);

return LMG2L["ScreenGui_1"], require;
